import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import type { Database } from '@/integrations/supabase/types';

type Invoice = Database['public']['Tables']['invoices']['Row'];
type InvoiceInsert = Database['public']['Tables']['invoices']['Insert'];
type InvoiceUpdate = Database['public']['Tables']['invoices']['Update'];
type InvoiceItem = Database['public']['Tables']['invoice_items']['Row'];
type InvoiceItemInsert = Database['public']['Tables']['invoice_items']['Insert'];
type Customer = Database['public']['Tables']['customers']['Row'];
type Company = Database['public']['Tables']['companies']['Row'];

export const useInvoices = () => {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState<(Invoice & { 
    customer?: Customer; 
    company?: Company;
    invoice_items?: InvoiceItem[];
  })[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchInvoices = async () => {
    try {
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          customer:customers(*),
          company:companies(*),
          invoice_items(*)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setInvoices(data || []);
    } catch (error) {
      console.error('Error fetching invoices:', error);
    } finally {
      setLoading(false);
    }
  };

  const createInvoice = async (invoiceData: Omit<InvoiceInsert, 'created_by' | 'invoice_number'>) => {
    try {
      const { data, error } = await supabase
        .from('invoices')
        .insert({
          ...invoiceData,
          created_by: user?.id || '',
          invoice_number: '' // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      await fetchInvoices();
      return data;
    } catch (error) {
      console.error('Error creating invoice:', error);
      throw error;
    }
  };

  const updateInvoice = async (id: string, updates: InvoiceUpdate) => {
    try {
      const { data, error } = await supabase
        .from('invoices')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      await fetchInvoices();
      return data;
    } catch (error) {
      console.error('Error updating invoice:', error);
      throw error;
    }
  };

  const deleteInvoice = async (id: string) => {
    try {
      const { error } = await supabase
        .from('invoices')
        .delete()
        .eq('id', id);

      if (error) throw error;
      await fetchInvoices();
    } catch (error) {
      console.error('Error deleting invoice:', error);
      throw error;
    }
  };

  const addInvoiceItem = async (invoiceId: string, item: Omit<InvoiceItemInsert, 'invoice_id' | 'total_price'>) => {
    try {
      const totalPrice = (item.quantity || 1) * (item.unit_price || 0);
      
      const { data, error } = await supabase
        .from('invoice_items')
        .insert({
          ...item,
          invoice_id: invoiceId,
          total_price: totalPrice
        })
        .select()
        .single();

      if (error) throw error;
      await fetchInvoices();
      return data;
    } catch (error) {
      console.error('Error adding invoice item:', error);
      throw error;
    }
  };

  const updateInvoiceItem = async (itemId: string, updates: Partial<InvoiceItem>) => {
    try {
      let finalUpdates = { ...updates };
      
      if (updates.quantity !== undefined || updates.unit_price !== undefined) {
        const currentItem = await supabase
          .from('invoice_items')
          .select('*')
          .eq('id', itemId)
          .single();

        if (currentItem.data) {
          const quantity = updates.quantity ?? currentItem.data.quantity;
          const unitPrice = updates.unit_price ?? currentItem.data.unit_price;
          finalUpdates.total_price = quantity * unitPrice;
        }
      }

      const { data, error } = await supabase
        .from('invoice_items')
        .update(finalUpdates)
        .eq('id', itemId)
        .select()
        .single();

      if (error) throw error;
      await fetchInvoices();
      return data;
    } catch (error) {
      console.error('Error updating invoice item:', error);
      throw error;
    }
  };

  const deleteInvoiceItem = async (itemId: string) => {
    try {
      const { error } = await supabase
        .from('invoice_items')
        .delete()
        .eq('id', itemId);

      if (error) throw error;
      await fetchInvoices();
    } catch (error) {
      console.error('Error deleting invoice item:', error);
      throw error;
    }
  };

  useEffect(() => {
    if (user) {
      fetchInvoices();

      const invoicesChannel = supabase
        .channel('invoices_changes')
        .on(
          'postgres_changes',
          {
            event: '*',
            schema: 'public',
            table: 'invoices'
          },
          () => fetchInvoices()
        )
        .subscribe();

      const itemsChannel = supabase
        .channel('invoice_items_changes')
        .on(
          'postgres_changes',
          {
            event: '*',
            schema: 'public',
            table: 'invoice_items'
          },
          () => fetchInvoices()
        )
        .subscribe();

      return () => {
        supabase.removeChannel(invoicesChannel);
        supabase.removeChannel(itemsChannel);
      };
    }
  }, [user]);

  return {
    invoices,
    loading,
    createInvoice,
    updateInvoice,
    deleteInvoice,
    addInvoiceItem,
    updateInvoiceItem,
    deleteInvoiceItem,
    refetch: fetchInvoices
  };
};