// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmkzovzexjqphdsciqop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ta3pvdnpleGpxcGhkc2NpcW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzU1OTcsImV4cCI6MjA3MDI1MTU5N30.jVwE3vzEPWSLS07qb1BZ_Zc-WGQFHEtM4OsabvTkiPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});